[package]
name = "tiny_pong"
version = "0.2.0"
edition = "2021"

[dependencies]
bevy = "0.14.1"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
incremental = false
debug = false
